import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Outlet, Link, useNavigate, useLocation } from 'react-router-dom';
import { ShieldCheck, LogOut, FileText } from 'lucide-react';
import { useCustomerAuth } from '../hooks/useCustomerPortal';
export const CustomerPortalLayout = () => {
    const { customer, logout } = useCustomerAuth();
    const navigate = useNavigate();
    const location = useLocation();
    const handleLogout = () => {
        logout();
        navigate('/customer/login');
    };
    const isActive = (path) => location.pathname === path;
    return (_jsxs("div", { className: "min-h-screen bg-slate-50 flex flex-col font-sans text-slate-800", children: [_jsx("header", { className: "bg-white border-b border-slate-200 sticky top-0 z-40 shadow-sm", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: "w-10 h-10 rounded-xl bg-gradient-to-tr from-purple-600 to-indigo-600 flex items-center justify-center text-white font-bold shadow-md shadow-purple-200", children: _jsx(ShieldCheck, { className: "w-6 h-6" }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("span", { className: "font-bold text-lg text-slate-900 tracking-tight", children: "DealFlow360" }), _jsx("span", { className: "px-2 py-0.5 text-xs font-semibold bg-purple-100 text-purple-700 rounded-full", children: "Customer Portal" })] }), _jsx("p", { className: "text-xs text-slate-500 font-medium", children: customer?.company || 'Commercial Partner Portal' })] })] }), _jsx("nav", { className: "hidden md:flex items-center space-x-1", children: _jsxs(Link, { to: "/customer/quotes", className: `flex items-center space-x-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${isActive('/customer/quotes') || location.pathname.startsWith('/customer/quotes/')
                                        ? 'bg-purple-50 text-purple-700 font-semibold'
                                        : 'text-slate-600 hover:text-slate-900 hover:bg-slate-100'}`, children: [_jsx(FileText, { className: "w-4 h-4" }), _jsx("span", { children: "My Quotations" })] }) }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { className: "flex items-center space-x-2.5 bg-slate-100 px-3 py-1.5 rounded-full border border-slate-200", children: [_jsx("div", { className: "w-7 h-7 rounded-full bg-purple-600 text-white flex items-center justify-center text-xs font-bold", children: customer?.name ? customer.name.charAt(0).toUpperCase() : 'C' }), _jsxs("div", { className: "hidden sm:block text-left pr-1", children: [_jsx("div", { className: "text-xs font-bold text-slate-800 leading-none", children: customer?.name || 'Valued Customer' }), _jsx("div", { className: "text-[10px] text-slate-500 leading-tight", children: customer?.email })] })] }), _jsxs("button", { onClick: handleLogout, className: "flex items-center space-x-1.5 px-3 py-1.5 text-xs font-medium text-slate-600 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors border border-transparent hover:border-red-200", title: "Log out of Customer Portal", children: [_jsx(LogOut, { className: "w-4 h-4" }), _jsx("span", { className: "hidden sm:inline", children: "Logout" })] })] })] }) }) }), _jsx("main", { className: "flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8", children: _jsx(Outlet, {}) }), _jsx("footer", { className: "bg-white border-t border-slate-200 py-6 text-center text-xs text-slate-500", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-2", children: [_jsxs("div", { children: ["\u00A9 ", new Date().getFullYear(), " DealFlow360 Enterprise Commerce. All rights reserved."] }), _jsxs("div", { className: "flex items-center space-x-4 text-slate-400", children: [_jsx("span", { children: "Secure SSL Encrypted" }), _jsx("span", { children: "\u2022" }), _jsx("span", { children: "Customer Terms & Confidentiality Guaranteed" })] })] }) })] }));
};
//# sourceMappingURL=CustomerPortalLayout.js.map