import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const BackorderQueue = ({ backorders }) => {
    return (_jsxs("div", { className: "bg-white rounded-xl shadow-sm border border-slate-200 p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-bold text-slate-900", children: "Backorder Queue & Stock Deficits" }), _jsx("p", { className: "text-sm text-slate-500", children: "Unfulfilled line items pending multi-warehouse replenishment" })] }), _jsxs("span", { className: "px-3 py-1 bg-rose-50 text-rose-700 text-xs font-semibold rounded-full border border-rose-200", children: [backorders.length, " Active Backorder Orders"] })] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left text-sm border-collapse", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-slate-50 border-b border-slate-200 text-slate-700 font-semibold", children: [_jsx("th", { className: "p-3", children: "Order / Fulfillment Ref" }), _jsx("th", { className: "p-3", children: "Customer" }), _jsx("th", { className: "p-3", children: "Backordered Items" }), _jsx("th", { className: "p-3 text-right", children: "Shortage Quantity" }), _jsx("th", { className: "p-3 text-center", children: "Status" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-200 text-slate-600", children: backorders.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-6 text-center text-slate-400", children: "No active backorders currently in queue." }) })) : (backorders.map((record) => {
                                const customerName = typeof record.customerId === 'object' ? record.customerId.name : 'Customer';
                                return record.backorders.map((bo, idx) => {
                                    const prodName = typeof bo.productId === 'object' ? bo.productId.name : 'Product';
                                    const prodSku = typeof bo.productId === 'object' ? bo.productId.sku : '';
                                    return (_jsxs("tr", { className: "hover:bg-slate-50 transition-colors", children: [_jsx("td", { className: "p-3 font-semibold text-slate-900", children: record.fulfillmentNumber }), _jsx("td", { className: "p-3", children: customerName }), _jsxs("td", { className: "p-3", children: [_jsx("div", { className: "font-medium text-slate-900", children: prodName }), _jsxs("div", { className: "text-xs text-slate-400 font-mono", children: ["SKU: ", prodSku] })] }), _jsxs("td", { className: "p-3 text-right font-bold text-rose-600", children: [bo.quantityBackordered, " units"] }), _jsx("td", { className: "p-3 text-center", children: bo.status === 'RESOLVED' ? (_jsx("span", { className: "px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-100 text-emerald-800", children: "Auto-Resolved" })) : (_jsx("span", { className: "px-2.5 py-0.5 rounded-full text-xs font-semibold bg-rose-100 text-rose-800", children: "Pending Stock" })) })] }, `${record._id}-${idx}`));
                                });
                            })) })] }) })] }));
};
//# sourceMappingURL=BackorderQueue.js.map