import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const ExportManifestModal = ({ isOpen, onClose }) => {
    if (!isOpen)
        return null;
    return (_jsx("div", { className: "fixed inset-0 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 z-50", children: _jsxs("div", { className: "bg-white rounded-2xl max-w-xl w-full p-6 shadow-2xl border border-purple-100", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-slate-100 pb-4 mb-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-bold text-slate-900", children: "Digital Dispatch Manifest (PDF Export)" }), _jsx("p", { className: "text-xs text-slate-500", children: "Quote Q-2025-0842 \u00B7 Acme Industries Ltd." })] }), _jsx("button", { onClick: onClose, className: "text-slate-400 hover:text-slate-600 font-bold", children: "\u2715" })] }), _jsxs("div", { className: "bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-3 font-mono text-xs text-slate-700 mb-6", children: [_jsxs("div", { className: "flex justify-between font-bold text-slate-900 border-b pb-2", children: [_jsx("span", { children: "DEALFLOW360 LOGISTICS MANIFEST" }), _jsx("span", { children: "DATE: 2026-09-05" })] }), _jsx("div", { children: "CUSTOMER: Acme Industries Ltd." }), _jsx("div", { children: "DELIVERABLE BATCH #1: 6x Laptop X1 Carbon -> Main Warehouse (Bhiwandi) [BlueDart Apex]" }), _jsx("div", { children: "DELIVERABLE BATCH #2: 4x Laptop X1 Carbon -> East Depot (Kolkata) [Delhivery Freight]" }), _jsx("div", { children: "SAAS LICENSE: 10x Cloud RevOps Seats [Automated API Token]" }), _jsx("div", { children: "SERVICES: 1x Onsite Implementation Pack [Field Engineer Assigned]" }), _jsx("div", { className: "pt-2 border-t font-bold text-purple-900", children: "STATUS: VERIFIED OPTIMAL SPLIT RELEASED" })] }), _jsxs("div", { className: "flex justify-end gap-3", children: [_jsx("button", { onClick: onClose, className: "px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100 rounded-xl", children: "Close" }), _jsxs("button", { onClick: () => {
                                window.print();
                                onClose();
                            }, className: "px-5 py-2 text-xs font-bold text-white bg-purple-600 hover:bg-purple-700 rounded-xl shadow-md shadow-purple-600/20 flex items-center gap-1.5", children: [_jsx("span", { children: "\uD83D\uDDA8\uFE0F" }), " Print / Download PDF"] })] })] }) }));
};
//# sourceMappingURL=ExportManifestModal.js.map