import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const LogisticsIntelligencePanel = ({ onAcceptSplit, onToggleConsolidation, isConsolidatedMode, isConfirmed, }) => {
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-purple-50/50 border border-purple-100 p-4 rounded-2xl", children: [_jsxs("div", { className: "flex justify-between items-center text-xs pb-2 border-b border-purple-100", children: [_jsx("span", { className: "font-semibold text-slate-600", children: "Simulated Freight Variance:" }), _jsx("strong", { className: "text-purple-900 font-bold", children: isConsolidatedMode ? '+₹42,000 (Surcharge)' : '₹0 (Optimal Baseline)' })] }), _jsxs("div", { className: "flex justify-between items-center text-xs pt-2", children: [_jsx("span", { className: "font-semibold text-slate-600", children: "Lead Time Risk:" }), _jsx("strong", { className: isConsolidatedMode ? 'text-rose-600 font-bold' : 'text-emerald-600 font-bold', children: isConsolidatedMode ? 'High SLA Breach (6 Days)' : 'No SLA breach projected' })] })] }), _jsxs("div", { className: "bg-gradient-to-br from-purple-50 to-indigo-50/60 border border-purple-200/80 p-4 rounded-2xl", children: [_jsxs("div", { className: "flex items-center gap-1.5 text-xs font-extrabold text-purple-900 mb-1.5", children: [_jsx("span", { children: "\u2728" }), " Autonomous Deal Path"] }), _jsx("p", { className: "text-xs text-purple-950/80 leading-relaxed font-medium", children: isConsolidatedMode
                            ? 'Consolidating 10 units to Main Warehouse causes ₹42,000 freight surcharge and triggers VP Finance approval policy BR-482.'
                            : '6 Units Main + 4 Units East prevents ₹24,000 unallocated freight drain and avoids triggering VP Finance logistics exception policy BR-482.' })] }), _jsxs("div", { className: "bg-white border border-purple-100 p-4 rounded-2xl space-y-3.5", children: [_jsx("div", { className: "text-xs font-bold text-slate-900", children: "Inventory Health & Depletion Gauge" }), _jsxs("div", { children: [_jsxs("div", { className: "flex justify-between text-xs mb-1 font-semibold", children: [_jsx("span", { className: "text-slate-700", children: "Main Warehouse Stock Remaining:" }), _jsx("strong", { className: "text-slate-900", children: "8 Units left" })] }), _jsx("div", { className: "w-full bg-slate-100 rounded-full h-2 overflow-hidden mb-1", children: _jsx("div", { className: "bg-purple-600 h-2 rounded-full", style: { width: '57%' } }) }), _jsxs("div", { className: "flex justify-between text-[11px] text-slate-500 font-medium", children: [_jsx("span", { children: "Safety Floor: 5 units" }), _jsx("span", { className: "text-emerald-600 font-bold", children: "Healthy" })] })] }), _jsxs("div", { children: [_jsxs("div", { className: "flex justify-between text-xs mb-1 font-semibold", children: [_jsx("span", { className: "text-slate-700", children: "East Depot Stock Remaining:" }), _jsx("strong", { className: "text-slate-900", children: "5 Units left" })] }), _jsx("div", { className: "w-full bg-slate-100 rounded-full h-2 overflow-hidden mb-1", children: _jsx("div", { className: "bg-purple-600 h-2 rounded-full", style: { width: '55%' } }) }), _jsxs("div", { className: "flex justify-between text-[11px] text-slate-500 font-medium", children: [_jsx("span", { children: "Safety Floor: 3 units" }), _jsx("span", { className: "text-emerald-600 font-bold", children: "Healthy" })] })] })] }), _jsxs("div", { className: "space-y-2.5 pt-2", children: [_jsxs("button", { onClick: onAcceptSplit, disabled: isConfirmed, className: `w-full py-3 px-4 rounded-xl text-xs font-bold transition-all shadow-md flex items-center justify-center gap-2 ${isConfirmed
                            ? 'bg-emerald-600 text-white shadow-emerald-500/20'
                            : 'bg-purple-600 hover:bg-purple-700 text-white shadow-purple-600/30'}`, children: [_jsx("span", { children: isConfirmed ? '✓' : '☑' }), _jsx("span", { children: isConfirmed ? 'Allocation Released & Locked in DB' : 'Accept Suggested 6+4 Split' })] }), _jsx("button", { onClick: onToggleConsolidation, className: `w-full py-2.5 px-4 border rounded-xl text-xs font-bold transition-colors ${isConsolidatedMode
                            ? 'border-purple-600 bg-purple-50 text-purple-900'
                            : 'border-slate-300 hover:bg-slate-50 text-slate-700'}`, children: isConsolidatedMode
                            ? '↩ Restore Suggested 6+4 Split'
                            : 'Simulate Single-Hub Consolidation (Causes 3-day backorder)' })] }), _jsxs("div", { className: "bg-slate-50 border border-slate-200/80 p-4 rounded-2xl text-xs space-y-1", children: [_jsxs("div", { className: "flex items-center gap-1.5 text-slate-500 font-bold", children: [_jsx("span", { children: "\uD83D\uDCDC" }), " AUDIT TRAIL LOG"] }), _jsx("p", { className: "text-slate-600 font-mono text-[11px] leading-relaxed italic", children: "\"DealTwin engine auto-routed 6+4 split based on customer regional delivery sites (Mumbai HQ: 6 units, Kolkata Branch: 4 units).\"" })] })] }));
};
//# sourceMappingURL=LogisticsIntelligencePanel.js.map