export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Resources
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Business
  QUOTATION_NOT_EDITABLE = 'QUOTATION_NOT_EDITABLE',
  APPROVAL_ALREADY_ACTIONED = 'APPROVAL_ALREADY_ACTIONED',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  INVOICE_ALREADY_PAID = 'INVOICE_ALREADY_PAID',

  // Server
  SERVER_ERROR = 'SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
}
