import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, ArrowUpDown, ArrowRight, FileText, Loader2, AlertCircle } from 'lucide-react';
import { useCustomerQuotes } from '../hooks/useCustomerPortal';
export const CustomerQuotesPage = () => {
    const { data: quotes, isLoading, isError } = useCustomerQuotes();
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedStatus, setSelectedStatus] = useState('ALL');
    const [sortBy, setSortBy] = useState('date');
    if (isLoading) {
        return (_jsxs("div", { className: "flex items-center justify-center py-20 text-slate-500", children: [_jsx(Loader2, { className: "w-8 h-8 animate-spin text-purple-600 mr-2" }), _jsx("span", { className: "text-sm font-medium", children: "Loading your quotations..." })] }));
    }
    if (isError) {
        return (_jsxs("div", { className: "p-6 bg-red-50 border border-red-200 rounded-2xl text-red-700 text-sm", children: [_jsx(AlertCircle, { className: "w-5 h-5 mb-2 text-red-600" }), _jsx("span", { children: "Failed to load quotations. Please ensure you are authenticated." })] }));
    }
    let filtered = (quotes || []).filter((q) => {
        const matchesSearch = q.quotationNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
            q.companyName.toLowerCase().includes(searchTerm.toLowerCase());
        const matchesStatus = selectedStatus === 'ALL' || q.status.toUpperCase() === selectedStatus.toUpperCase();
        return matchesSearch && matchesStatus;
    });
    filtered.sort((a, b) => {
        if (sortBy === 'amount') {
            return b.total - a.total;
        }
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
    });
    return (_jsxs("div", { className: "space-y-6", children: [_jsx("div", { className: "flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 pb-4 border-b border-slate-200", children: _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-black text-slate-900 tracking-tight", children: "My Corporate Quotations" }), _jsx("p", { className: "text-xs text-slate-500 mt-1", children: "Review line pricing, add comments, request change adjustments, propose counter discounts, and confirm orders." })] }) }), _jsxs("div", { className: "bg-white rounded-2xl border border-slate-200 p-4 shadow-xs flex flex-col md:flex-row items-center justify-between gap-4", children: [_jsxs("div", { className: "relative w-full md:w-72", children: [_jsx(Search, { className: "w-4 h-4 text-slate-400 absolute left-3 top-2.5" }), _jsx("input", { type: "text", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), placeholder: "Search by quote # or company...", className: "w-full text-xs bg-slate-50 border border-slate-200 rounded-xl pl-9 pr-3 py-2 text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500" })] }), _jsx("div", { className: "flex items-center space-x-1 bg-slate-100 p-1 rounded-xl w-full md:w-auto overflow-x-auto", children: ['ALL', 'SENT', 'UNDER NEGOTIATION', 'CONFIRMED'].map((st) => (_jsx("button", { onClick: () => setSelectedStatus(st), className: `px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-all ${selectedStatus === st
                                ? 'bg-white text-purple-700 shadow-xs font-bold'
                                : 'text-slate-600 hover:text-slate-900'}`, children: st === 'ALL' ? 'All Quotes' : st }, st))) }), _jsxs("div", { className: "flex items-center space-x-2 text-xs font-medium text-slate-600 self-end md:self-auto", children: [_jsx(ArrowUpDown, { className: "w-3.5 h-3.5 text-slate-400" }), _jsx("span", { children: "Sort by:" }), _jsxs("select", { value: sortBy, onChange: (e) => setSortBy(e.target.value), className: "text-xs font-bold bg-slate-50 border border-slate-200 rounded-lg px-2 py-1 text-slate-800 focus:outline-none", children: [_jsx("option", { value: "date", children: "Newest Date" }), _jsx("option", { value: "amount", children: "Highest Total" })] })] })] }), filtered.length === 0 ? (_jsxs("div", { className: "bg-white rounded-2xl border border-slate-200 p-12 text-center max-w-md mx-auto", children: [_jsx("div", { className: "w-12 h-12 rounded-full bg-slate-100 text-slate-400 mx-auto flex items-center justify-center mb-3", children: _jsx(FileText, { className: "w-6 h-6" }) }), _jsx("h3", { className: "text-sm font-bold text-slate-800", children: "No Quotations Found" }), _jsx("p", { className: "text-xs text-slate-500 mt-1", children: "No quotations matched your selected search criteria or status filter." })] })) : (_jsxs(_Fragment, { children: [_jsx("div", { className: "hidden md:block bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden", children: _jsxs("table", { className: "w-full text-left text-xs", children: [_jsx("thead", { className: "bg-slate-50 text-slate-500 uppercase text-[10px] font-bold border-b border-slate-200", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3.5", children: "Quote Reference" }), _jsx("th", { className: "px-6 py-3.5", children: "Customer & Tier" }), _jsx("th", { className: "px-6 py-3.5", children: "Validity Date" }), _jsx("th", { className: "px-6 py-3.5", children: "Status" }), _jsx("th", { className: "px-6 py-3.5 text-right", children: "Grand Total" }), _jsx("th", { className: "px-6 py-3.5 text-right", children: "Action" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-100 font-medium", children: filtered.map((quote) => (_jsxs("tr", { className: "hover:bg-purple-50/20 transition-colors", children: [_jsxs("td", { className: "px-6 py-4", children: [_jsx("div", { className: "font-extrabold text-slate-900", children: quote.quotationNumber }), _jsxs("div", { className: "text-[10px] text-slate-400", children: [quote.lineCount, " items"] })] }), _jsxs("td", { className: "px-6 py-4", children: [_jsx("div", { className: "text-slate-800 font-semibold", children: quote.companyName }), _jsx("div", { className: "text-[10px] text-slate-400", children: quote.customerName })] }), _jsx("td", { className: "px-6 py-4 text-slate-600", children: new Date(quote.validUntil).toLocaleDateString(undefined, {
                                                    month: 'short',
                                                    day: 'numeric',
                                                    year: 'numeric',
                                                }) }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: `inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-bold ${quote.status === 'CONFIRMED'
                                                        ? 'bg-emerald-100 text-emerald-800 border border-emerald-200'
                                                        : quote.status === 'UNDER NEGOTIATION'
                                                            ? 'bg-amber-100 text-amber-800 border border-amber-200'
                                                            : 'bg-purple-100 text-purple-800 border border-purple-200'}`, children: quote.status }) }), _jsxs("td", { className: "px-6 py-4 text-right", children: [_jsxs("div", { className: "font-black text-slate-900", children: ["$", quote.total.toLocaleString()] }), _jsx("div", { className: "text-[10px] text-slate-400", children: quote.currency })] }), _jsx("td", { className: "px-6 py-4 text-right", children: _jsxs(Link, { to: `/customer/quotes/${quote.id}`, className: "inline-flex items-center space-x-1 px-3 py-1.5 bg-purple-50 hover:bg-purple-100 text-purple-700 rounded-lg font-bold transition-colors text-xs", children: [_jsx("span", { children: "Review & Act" }), _jsx(ArrowRight, { className: "w-3.5 h-3.5" })] }) })] }, quote.id))) })] }) }), _jsx("div", { className: "md:hidden space-y-3", children: filtered.map((quote) => (_jsxs("div", { className: "bg-white rounded-2xl border border-slate-200 p-4 shadow-xs space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: "font-black text-slate-900 text-sm", children: quote.quotationNumber }), _jsx("span", { className: `px-2.5 py-0.5 rounded-full text-[10px] font-bold ${quote.status === 'CONFIRMED'
                                                ? 'bg-emerald-100 text-emerald-800'
                                                : quote.status === 'UNDER NEGOTIATION'
                                                    ? 'bg-amber-100 text-amber-800'
                                                    : 'bg-purple-100 text-purple-800'}`, children: quote.status })] }), _jsxs("div", { className: "text-xs text-slate-600 space-y-0.5", children: [_jsxs("div", { children: ["Company: ", _jsx("span", { className: "font-semibold text-slate-900", children: quote.companyName })] }), _jsxs("div", { children: ["Valid until: ", new Date(quote.validUntil).toLocaleDateString()] })] }), _jsxs("div", { className: "flex items-center justify-between pt-2 border-t border-slate-100", children: [_jsxs("div", { children: [_jsx("div", { className: "text-[10px] text-slate-400 uppercase font-bold", children: "Total" }), _jsxs("div", { className: "text-base font-black text-slate-900", children: ["$", quote.total.toLocaleString(), " ", _jsx("span", { className: "text-xs font-medium text-slate-500", children: quote.currency })] })] }), _jsxs(Link, { to: `/customer/quotes/${quote.id}`, className: "inline-flex items-center space-x-1 px-3 py-1.5 bg-purple-600 text-white rounded-xl font-bold text-xs shadow-xs", children: [_jsx("span", { children: "View Detail" }), _jsx(ArrowRight, { className: "w-3.5 h-3.5" })] })] })] }, quote.id))) })] }))] }));
};
//# sourceMappingURL=CustomerQuotesPage.js.map